### ISSUE TITLE
Implement MidenVM proof verifier

### ISSUE THREAD

**Issue by wraitii** [Hyle-org/hyle#25]
Miden VM is a zero-knowledge virtual machine written in Rust built by the Polygon team.

The purpose of this issue is to implement verification of MidenVM proofs using the provided backend https://crates.io/crates/miden-verifier.

This should be done using a subprocess call similar to our `risczero` implementation (https://github.com/Hyle-org/hyle-risc-zero-verifier) to a rust Miden verifier.

The Miden rust crate documents exactly how it works. You can also check https://github.com/0xPolygonMiden/miden-vm for further documentation about how it works.

Additionally, the matching verifier must be implemented in the verifier repository -> See https://github.com/Hyle-org/verifiers-for-hyle/issues/9

**Comment by juandiegocv27** [comment]
Hi, could I assigned to this issue @wraitii

**Comment by Osatuyi** [comment]
Hi @wraitii please can this be assigned to me.

**Comment by dragan2234** [comment]
Hi @wraitii I'm interested in this issue, let me know if I can take it

**Comment by wraitii** [comment]
> Hi @wraitii I'm interested in this issue, let me know if I can take it

Hey @dragan2234 ! Assigned you, go ahead !
