### ISSUE TITLE
Implement Kimchi (o1js) proof verifier

### ISSUE THREAD

**Issue by wraitii** [Hyle-org/hyle#26]
Implement verification of O1JS proofs using the Kimchi proving system.
This should be done using a subprocess call a rust verifier, similar to our `risczero` implementation.
Kimchi repository lives here: https://github.com/o1-labs/proof-systems

An example program should be given as well.

Additionally, the matching verifier must be implemented in the verifier repository → https://github.com/Hyle-org/verifiers-for-hyle/issues/10

**Comment by fabrobles92** [comment]
Hello I am Fabricio Robles, I have contributed to other open source web3 projects such as Dojo Engine and I'd like to work on this one. :D

**Comment by wraitii** [comment]
Hey @fabrobles92 , awesome ! Not sure how hard this issue would be for you, but feel free to try it out.

We have a public TG at https://t.me/+daA5zWOJGEQ3NGE0 if you have questions

**Comment by fabrobles92** [comment]
@wraitii Hello, after taking a look at this issue. I think it is beyond my technical level. I prefer to step out and give a more advanced developer a chance to work on this one.

**Comment by wraitii** [comment]
No problem, thanks for the transparency.

**Comment by JuanPabloRodriguezC** [comment]
Hello @wraitii! I’m Juan and I’m new to OSS, I have been wanting to work on zkp projects. I’d love to have a go at this issue .

**Comment by wraitii** [comment]
Hey @JuanPabloRodriguezC , this is an advanced issue, do you have prior knowledge of Halo2?

**Comment by brewedBorrows** [comment]
Hi @s0lness Can I work on this issue along with adding the verifier [here](https://github.com/Hyle-org/verifiers-for-hyle/issues/10)?

**Comment by JuanPabloRodriguezC** [comment]
Hi, I do not. I think its best to assign someone else.
