### ISSUE TITLE
Implement verification for Halo2 ZK proofs

### ISSUE THREAD

**Issue by wraitii** [Hyle-org/hyle#27]
The purpose of this issue is to implement verification of Halo2 proofs on Hylé. 

This should be done using a subprocess call a rust verifier, similar to our `risczero` implementation.
See instructions on https://github.com/axiom-crypto/halo2-scaffold/ for integration

Additionally, the matching verifier must be implemented in the verifier repository → https://github.com/Hyle-org/verifiers-for-hyle/issues/11

This PR is related to the “WebAuthn signer support” PR → https://github.com/Hyle-org/webauthn-identity-provider/issues/1

**Comment by Osatuyi** [comment]
@wraitii I'll like to hop on this. Please assign it to me.

**Comment by RajeshRk18** [comment]
Shall I take up this?

**Comment by wraitii** [comment]
> Shall I take up this?

If you're still up for this, go ahead :)

**Comment by RajeshRk18** [comment]
> > Shall I take up this?
> 
> If you're still up for this, go ahead :) 

Yeah! If time permits, I'll take other verifiers too!

**Comment by RajeshRk18** [comment]
@wraitii  For the prover and verifier circuits, what will be the inputs?

**Comment by wraitii** [comment]
> @wraitii Is the prover and verifier for P256 sig? Like I need to write verifier circuit for it?

In principle we want a general verifier - you should take a Verification Key (or similar) and a proof and output whether the proof is correct or not.

**Comment by RajeshRk18** [comment]
> > @wraitii Is the prover and verifier for P256 sig? Like I need to write verifier circuit for it?
> 
> In principle we want a general verifier - you should take a Verification Key (or similar) and a proof and output whether the proof is correct or not.

Like in the axiom's halo2 scaffold right?

Here is how it will look like;

- A separate repo for halo2 prover
- A verifier in the verifier repo

**Comment by wraitii** [comment]
> Like in the axiom's halo2 scaffold right?
> 
> * A separate repo for halo2 prover
> * A verifier in the verifier repo

Most likely, not really familiar with the axiom scaffold.
We don't per-se need a prover, but an example application would be good.

**Comment by wraitii** [comment]
> Can i work on this?

Hey @guha-rahul , I've assigned you
