### ISSUE TITLE
Implement boojum proof verifier

### ISSUE THREAD

**Issue by wraitii** [Hyle-org/hyle#28]
Boojum is zkSync’s zkVM. The purpose of this issue is to add support for Boojum proofs on Hylé so we can settle zkSync zkRollups.

This should be done using a subprocess call a rust verifier, similar to our `risczero` implementation.
See instructions on https://github.com/matter-labs/era-boojum for integration

Additionally, the matching verifier must be implemented in the verifier repository → https://github.com/Hyle-org/verifiers-for-hyle/issues/12

**Comment by wugalde19** [comment]
HI @wraitii , I'd love to take care of this one

This project sounds really interesting to me
Looks like a great opportunity to learn more about it

Could you please tell me if you have a Telegram group where I can introduce myself and ask a few questions?

**Comment by wraitii** [comment]
Hey @wugalde19 - this issue might be quite difficult.

We have a public TG at https://t.me/+daA5zWOJGEQ3NGE0.

**Comment by hhamud** [comment]
can I grab this one @wraitii

**Comment by jedstroke** [comment]
@wraitii Can I tackle this issue gracefully?

**Comment by wraitii** [comment]
Hey @hhamud , @jedstroke , do you have prior knowledge of boojum ?

**Comment by hhamud** [comment]
> Hey @hhamud , @jedstroke , do you have prior knowledge of boojum ?

yes

**Comment by wraitii** [comment]
> > Hey @hhamud , @jedstroke , do you have prior knowledge of boojum ?
> 
> yes

Awesome ! I've assigned it to you 👍

**Comment by hhamud** [comment]
@wraitii it seems you've already assigned this issue to someone else.

can you clarify if this is still free to work on as I don't want to waste time replicating work.

https://github.com/Hyle-org/verifiers-for-hyle/issues/12

**Comment by wugalde19** [comment]
> > @wraitii it seems you've already assigned this issue to someone else.
> 
> Mh sorry about that, should have checked. I'll ping over there to see if the other assignee is still on it or stuck.

@wraitii If not assigned I'm also interested in working on this
Last time it was mentioned to me it was quite difficult but I'm willing to take on this challenge with your team's assistance of course
